### ISSUE TITLE
missing explanation 

### ISSUE THREAD

**Issue by marikap00** [UniprJRC/FSDA#70]
In the ace.m file (FSDA -> toolbox -> regression -> ace.m) there's a missing explanation to line 258  

![image](https://github.com/UniprJRC/FSDA/assets/146754754/2da79522-14d7-4cd9-bb63-aabfd42761e2)

%% ct vector containing the... **?**

**Comment by MarcoRianiUNIPR** [comment]
Done thank you for spotting it
